trigger:
- master

stages:
- stage: build
  jobs:
    - template: .azure/build-template.yml  # Template reference
      parameters:
        name: Dotnet-cli
        vmImage: 'ubuntu-latest'
        artifact: dotnet-cli
