trigger:
- master

pr:
- master

stages:
- stage: test
  jobs:
    - template: .azure/build-template.yml  # Template reference
      parameters:
        name: dotnet_cli
        vmImage: 'ubuntu-latest'
        artifact: dotnet_cli

- stage: build
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
    - template: .azure/build-template.yml  # Template reference
      parameters:
        name: linux
        vmImage: 'ubuntu-latest'
        artifact: linux
    - template: .azure/build-template.yml  # Template reference
      parameters:
        name: windows
        vmImage: 'windows-2019'
        artifact: windows
    - template: .azure/build-template.yml  # Template reference
      parameters:
        name: macos
        vmImage: 'macOS-10.14'
        artifact: macos

- stage: docker
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
   - job: dockerhub
     continueOnError: false
     steps:
      - task: Docker@2
        inputs:
          command: 'build'
          Dockerfile: '**/Dockerfile'
      - task: Docker@2
        inputs:
          containerRegistry: 'DockerHub'
          repository: 'mattiascibien/image-search-bot'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |
            $(Build.BuildNumber)
            latest