trigger:
- master

pr:
- master

stages:
- stage: test
  jobs:
    - template: .azure/build-test.yml  # Template reference

- stage: build
  #condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
    - template: .azure/build-template.yml  # Template reference
      parameters:
        name: linux
        vmImage: 'ubuntu-latest'
        artifact: linux
        runtime: linux-x64
    - template: .azure/build-template.yml  # Template reference
      parameters:
        name: windows
        vmImage: 'windows-2019'
        artifact: windows
        runtime: win-x64
    - template: .azure/build-template.yml  # Template reference
      parameters:
        name: macos
        vmImage: 'macOS-10.14'
        artifact: macos
        runtime: osx-x64
    - job: github
      dependsOn:
      - windows
      - macos
      - linux
      steps:
        - task: DownloadPipelineArtifact@2
          inputs:
            buildType: 'current'
            targetPath: '$(Pipeline.Workspace)'
        - task: GitHubRelease@0
          inputs:
            gitHubConnection: 'github.com'
            repositoryName: 'mattiascibien/image-search-bot'
            action: 'create'
            target: '$(Build.BuildNumber)'
            tagSource: 'manual'
            tag: 'v$(Build.BuildNumber)'
            title: 'Release $(Build.BuildNumber)'
            assets: '$(Pipeline.Workspace)/**/*.zip'
            isDraft: true
            addChangeLog: false

- stage: docker
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
   - job: dockerhub
     continueOnError: false
     steps:
      - task: Docker@2
        inputs:
          command: 'build'
          Dockerfile: '**/Dockerfile'
      - task: Docker@2
        inputs:
          containerRegistry: 'DockerHub'
          repository: 'mattiascibien/image-search-bot'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |
            $(Build.BuildNumber)
            latest