trigger:
- master

pr:
- master

stages:
- stage: test
  jobs:
    - template: .azure/build-test.yml  # Template reference

- stage: build
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
    - template: .azure/build-template.yml  # Template reference
      parameters:
        name: linux
        vmImage: 'ubuntu-latest'
        artifact: linux
        runtime: linux-x64
    - template: .azure/build-template.yml  # Template reference
      parameters:
        name: windows
        vmImage: 'windows-2022'
        artifact: windows
        runtime: win-x64
    - template: .azure/build-template.yml  # Template reference
      parameters:
        name: macos
        vmImage: 'macOS-10.15'
        artifact: macos
        runtime: osx-x64

- stage: github
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
    - job: github_release
      steps:
        - checkout: none
        - task: DownloadPipelineArtifact@2
          inputs:
            buildType: 'current'
            targetPath: '$(Pipeline.Workspace)'
        - task: GitHubRelease@0
          inputs:
            gitHubConnection: 'github.com'
            repositoryName: 'mattiascibien/image-search-bot'
            tagSource: manual
            tag: v$(Build.BuildNumber)
            title: Release v$(Build.BuildNumber)
            assets: '$(Pipeline.Workspace)/**/*.zip'
            isDraft: false
            addChangeLog: true

- stage: docker
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
   - job: dockerhub
     continueOnError: false
     steps:
      - task: Docker@2
        displayName: 'Login To DockerHub'
        inputs:
          containerRegistry: 'DockerHub'
          command: 'login'
      - bash: docker buildx create --bootstrap --driver docker-container --use --platform linux/amd64,linux/arm64
        displayName: 'Create multi-arch Docker Builder'
      - bash: docker buildx build --no-cache --push --platform linux/amd64,linux/arm64 -f Dockerfile --tag mattiascibien/image-search-bot:latest --tag mattiascibien/image-search-bot:$(Build.BuildNumber) .
        displayName: 'Build and push Image'
