trigger:
- master

stages:
- stage: build_standalone
  jobs:
  - job: build_linux
    pool:
      vmImage: 'ubuntu-latest'
    continueOnError: false
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '''**/*.csproj'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '**/*.csproj'
        zipAfterPublish: false
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: 'drop'
