trigger:
- master

pr:
- master

stages:
- stage: test
  jobs:
    - template: .azure/build-test.yml  # Template reference

- stage: build
  #condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
    - template: .azure/build-template.yml  # Template reference
      parameters:
        name: linux
        vmImage: 'ubuntu-latest'
        artifact: linux
        runtime: linux-x64
    - template: .azure/build-template.yml  # Template reference
      parameters:
        name: windows
        vmImage: 'windows-2019'
        artifact: windows
        runtime: win-x64
    - template: .azure/build-template.yml  # Template reference
      parameters:
        name: macos
        vmImage: 'macOS-10.14'
        artifact: macos
        runtime: osx-x64

- stage: github
  #condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
    - job: release
      steps:
        - checkout: none
        - task: DownloadPipelineArtifact@2
          inputs:
            buildType: 'current'
            targetPath: '$(Pipeline.Workspace)'
        - task: GitHubRelease@0
          inputs:
            gitHubConnection: 'github.com'
            repositoryName: 'mattiascibien/image-search-bot'
            tagSource: manual
            tag: v$(Build.BuildNumber)
            title: Release v$(Build.BuildNumber)
            assets: '$(Pipeline.Workspace)/**/*.zip'
            isDraft: false
            addChangeLog: true

- stage: snap
  #condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
    - job: release
      steps:
        - bash: docker pull snapcore/snapcraft:stable
        - bash: docker run -v "$PWD":/build -w /build snapcore/snapcraft:stable snapcraft
        - bash: mv *.snap $(build.artifactstagingdirectory)
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(build.artifactstagingdirectory)'
            ArtifactName: 'snap'

- stage: docker
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
   - job: dockerhub
     continueOnError: false
     steps:
      - task: Docker@2
        inputs:
          command: 'build'
          Dockerfile: '**/Dockerfile'
      - task: Docker@2
        inputs:
          containerRegistry: 'DockerHub'
          repository: 'mattiascibien/image-search-bot'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |
            $(Build.BuildNumber)
            latest