parameters:
  name: ''
  artifact: ''
  runtime: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  continueOnError: false
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: sdk
      version: 6.0.x
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '**/*.csproj'
      zipAfterPublish: true
      arguments: --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory) --self-contained -r ${{ parameters.runtime }}
  - pwsh: mv $(build.artifactstagingdirectory)/s.zip $(build.artifactstagingdirectory)/${{ parameters.artifact }}.zip
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: ${{ parameters.artifact }}
